In [2]:
import numpy as np
import matplotlib.pyplot as plt

In [10]:
S = 12
df = 1

# in the order of U D L R
dynamic = {
    0: [1, 0, 0, 3],
    1: [2, 0, 1, 1],
    2: [2, 1, 2, 4],
    3: [3, 3, 0, 5],
    4: [4, 4, 2, 7],
    5: [6, 5, 3, 8],
    6: [7, 5, 6, 9],
    7: [7, 6, 4, 10],
    8: [9, 8, 5, 8],
    9: [11, 11, 11, 11],
    10: [11, 11, 11, 11],
    11: [11, 11, 11, 11]
}

# return a vector of 4 actions
def reward(s):
    if s == 11:
        return np.zeros(4)
    else:
        if s == 9:
            return -10*np.ones(4)
        elif s == 10:
            return 10*np.ones(4)
        else:
            return -1*np.ones(4)


In [11]:
%%timeit -n100 -r3
error = 1e-4
pi = 0.25*np.ones(shape=(S, 4))
V = np.zeros(S)
# policy evaluation
Delta = 10
while Delta > error:
    Delta = 0
    for s in range(S):
        v = V[s]
        V[s] = pi[s].dot(reward(s) + df*V[dynamic[s]])
        Delta = max(Delta, abs(v - V[s]))

26.1 ms ± 98.1 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)


In [12]:
%%timeit -n100 -r3
error = 1e-4
pi = 0.25*np.ones(shape=(S, 4))
V = np.zeros(S)
# policy evaluation
Delta = 10
while Delta > error:
    Delta = 0
    for s in range(S-1,-1,-1):
        v = V[s]
        V[s] = pi[s].dot(reward(s) + df*V[dynamic[s]])
        Delta = max(Delta, abs(v - V[s]))

26.5 ms ± 331 µs per loop (mean ± std. dev. of 3 runs, 100 loops each)


In [7]:
# get optimal poilcy
error = 1e-4
pi = 0.25*np.ones(shape=(S, 4))
# V = np.random.normal(0, 1, S)
V = np.zeros(S)

term_flag = False

while not term_flag:
    # policy evaluation
    Delta = 10
    while Delta > error:
        Delta = 0
        for s in range(S):
            v = V[s]
            V[s] = pi[s].dot(reward(s) + df*V[dynamic[s]])
            Delta = max(Delta, abs(v - V[s]))

    # policy imporvement
    term_flag = True
    for s in range(S):
        p = np.array(pi[s])
        ai = np.argmax(reward(s) + df*V[dynamic[s]])
        a = np.zeros(4)
        a[ai] = 1.
        pi[s] = a
        # print(a, p)
        if np.linalg.norm(a-p) > 1e-4:
            term_flag = False
            
print(V, pi)

[  5.   6.   7.   6.   8.   7.   8.   9.   6. -10.  10.   0.] [[ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  0.  1.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  0.  1.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]
 [ 1.  0.  0.  0.]]


In [8]:
%%timeit -n100 -r3
error = 1e-4
V = np.zeros(S)
# policy evaluation
Delta = 10
while Delta > error:
    Delta = 0
    for s in range(S):
        v = V[s]
        V[s] = pi[s].dot(reward(s) + df*V[dynamic[s]])
        Delta = max(Delta, abs(v - V[s]))

1.02 ms ± 107 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)


In [9]:
%%timeit -n100 -r3
error = 1e-4
V = np.zeros(S)
# policy evaluation
Delta = 10
while Delta > error:
    Delta = 0
    for s in range(S-1,-1,-1):
        v = V[s]
        V[s] = pi[s].dot(reward(s) + df*V[dynamic[s]])
        Delta = max(Delta, abs(v - V[s]))

418 µs ± 17.1 µs per loop (mean ± std. dev. of 5 runs, 100 loops each)
